### ISSUE TITLE
Q: Android app that supports rtsp stream

### ISSUE THREAD

**Issue by pergolafabio** [tommyjlong/app_rtsp_sip#1]
Hi, question...

I'm looking for an intercom solutiion... my doorstation sends early media in 183 session, so if i call to a softphone, i can see video before i pickup... thats good , but early media (video) doesnt work on ringgroups

So including an RTSP stream is a good alternative... But what Android softphones do support RTSP streams?

thnx in advance

**Comment by tommyjlong** [comment]
I'm not quite sure of the application of app_rtsp_sip in your scenario. Maybe you can explain further.
But to answer your question, no I don't know of any softphones that support RTSP.

**Comment by pergolafabio** [comment]
well, i have an Hikvision outdoor intercom, i connected it to my asteriks as a SIP registration
the i created some new sip users, for the house members, who installed a softphone client on the android

So when someine is at the door, and pressed the call button, we get an incoming call on our android, i'm working with ring groups, so all is working fine ...but we dont see any early media, we dont see video on our softphone, before we pickup... 
The person who picksup, he is seeing video , so who is at the door...

If i dont use ringgroups, and just call a single sip user, then early video works, so the outdoor station is cabable of sending early media... but asterisk isnt able to send early media to ring groups....

so i was looking for an alternative way to share the video , maybe by intecting an RSTP in the header... but then i still need a softphone that is able to display the rtsp stream?

What is your use case? why are you intectting the rtsp stream? when are you showing this?

**Comment by pergolafabio** [comment]
You are talking about zoiper? I zoiber able to see the intected rtsp stream in the sip header?

**Comment by tommyjlong** [comment]
There are video doorbells (and several surveillance cameras) that use SIP for 1-way audio (towards the camera), but use RTSP for sending both video and 1-way audio (sourced from the camera).  If you have a SIP softphone (which knows nothing of RTSP), how does it connect a 2-way audio channel with the camera?  The use case is to connect a SIP client (softphone)'s 2-way audio with this doorbell.  

app_rtsp_sip is a proxy application (sitting on top of Asterisk) for receiving/sending audio media from/to the video doorbell (using both SIP and RTSP as described above), and Asterisk is used to connect the SIP client's audio stream with the app_rtsp_sip proxy's audio stream and in effect creates a 2-way audio stream from the doorbell to/from the SIP client.  To clarify further, RTSP is only seen by the doorbell and app_rtsp_sip.  RTSP is not seen by the SIP client and is not carried in any sip header.

After all of this you mask ask, what about the doorbell video?  In my use case, the doorbell provides video to Home Assistant just like any other camera in Home Assistant.  I have a Home Assistant web app that sees the video at any time I want to view it.  When someone rings the video doorbell, I view the video using the web app, and if I want to talk to the person at the door, the web app also has a SIP client that I use to call the doorbell via the app_rtsp_sip/Asterisk setup.

**Comment by pergolafabio** [comment]
Ah ok, you do it the other way around? Use HA too, with that new sip project and asterisk add-on

But in my case the door intercom initiaties the call to a ring group... So if I close the Lovelace view , I'm unable to pickup the call... Because there is no registration at that moment....

So you setup a conference and join the call with your sip card then from HA?

**Comment by tommyjlong** [comment]
When I want to talk to the person at the doorbell, I would use my lovelace card SIP Client (which by the way shows the video stream coming from the doorbell at all times).  It is configured to call extension 101 and Asterisk is configured to connect calls destined to 101 directly to the app_rtsp_sip app which in turn setups the 2-way audio stream with the doorbell.  The app_rtsp_sip app is not structured to work in a conference bridge, so it only handles one call/connection at a time with that doorbell.

I should add that I have an automation in HA that detects that a doorbell button has been pressed, and sends a persistent notification so that any user with HA web app can get the notification, go view the video, and then decide whether to connect to the doorbell's audio channel or not.

I am thinking on the fly a bit, but in you scenario your doorstation calling into Asterisk conference could be used as a trigger to send some kind of notification to HA (I came across this [link](https://bonani.tech/blink-lights-when-your-ip-phone-rings/) as a way to do this).  HA could use this similarly to my doorbell button being pressed and notify everyone.  Whoever gets the HA notification could view the video and decide whether to accept the call or not.  There are Lovelace SIP clients that can accept calls too.

**Comment by pergolafabio** [comment]
Yeah, already have an automation, I can grab a door press event with an ISAPi sensor, that's not an issue...

But the Lovelace card I'm using, when I close the view or companion app, the registration is gone .. so the doorstation is unable to call anyone ...

So I was thinking that the doorstation calls a conference... When I get a push notification, I open the sip card, then I join the call... So far so good, but if I end the call, the doorstation needs to leave the conference too

**Comment by tommyjlong** [comment]
Have you every tried to call the doorstation (when the doorstation is not already in a session) from your SIP Client?  If it will not accept an incoming call, then I'm not sure what else to try.  If it does accept an incoming call, then don't use a conference bridge.

**Comment by pergolafabio** [comment]
No, it doesn't accept a call, seems it doesn't see a ringing tone..

Some other guy on forum got it to work with below


exten => 200,1,Ringing()
exten => 200,2,wait(1)
exten => 200,3,ConfBridge(1000)

**Comment by tommyjlong** [comment]
I don't have any more ideas, and since app_rtsp_sip doesn't provide the needed solution, I will close this.
Best Regards

**Comment by pergolafabio** [comment]
Found the solution, with originate, but only using with AMI, then there is an option to define early media, this is not possible with the originate app itself, or Ari, only with AMI
